# Specify Version Of docker-compose
version: '3'

# Define Containers To Start
services:

  # Name 'mysql'
  mysql:
    # Build The Container From Folder
    build: ../mysql
    # Mount folder for database
    volumes:
      - ../data/data_mysql:/var/lib/mysql
    ports:
      - 3307:3306

  # Name 'python'
  python:
    # Build The Container From Folder
    build: ../python
    # Mount folder with data-files
    volumes:
      - ../build:/build
      - ../files:/files
    # Link The Container To The 'mysql' Service
    links:
      - mysql
    # Wait For The mysql Service To Start
    depends_on:
      - mysql
    command: python files/03_kmeans_create_model.py
