# Specify Version Of docker-compose
version: '3'

# Define Containers To Start
services:  

  # Name 'mysql'
  mysql:
    # Build The Container From Folder
    build: ../mysql
    # Mount folder for database
    volumes:
      - ../data/data_mysql:/var/lib/mysql
    ports:
      - 3307:3306

  # Name 'python'
  python:
    # Build The Container From Folder
    build: ../python
    # Mount folder with data-files
    volumes:
      - ../files:/files
      - ../build:/build
    # Link The Container To The Services
    links:
      - mysql
    # Wait For The Services To Start
    depends_on:
      - mysql
    command: python files/12_create_germany_plot.py
